services:
  codeproject-ai:
    hostname: codeproject-ai
    image: docker.io/codeproject/ai-server:cuda12_2-2.8.0
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      Modules:ObjectDetectionYOLOv8:AutoStart: 'true'
      Modules:ALPR:AutoStart: 'true'
      Server:InstallModules:InitialModules: 
      Server:MeshOptions:Enable: 'true'
      Server:MeshOptions:EnableStatusBroadcast: 'false'
      Server:MeshOptions:EnableStatusMonitoring: 'true'
      Server:MeshOptions:AllowRequestForwarding: 'true'
      Server:MeshOptions:KnownMeshHostnames: '[ "k8s-nginx.k8s.lan" ]'
      Server:ModuleOptions:InitialModules: 'ObjectDetectionYOLOv8; ALPR'
    ports:
      - "32168:32168"
    volumes:
      - codeproject_ai_config:/etc/codeproject/ai
      - codeproject_ai_modules:/app/modules
    restart: always
volumes:
  codeproject_ai_config:
  codeproject_ai_modules:

